services:
  backend:
    image: algoback
    ports:
      - 8080:8080
    volumes:
      - algosocial:/usr/app/db/

  frontend:
    image: algofront
    ports:
      - 3000:3000

volumes:
  algosocial: